name: 🐞 Bug report
description: Report a bug or an issue.
title: 'bug: '
labels: ['Bug report']
body:
  - type: markdown
    attributes:
      value: |
        # ReVanced Extended bug report

        Before creating a new bug report, please keep the following in mind:

        - **Do not submit a duplicate bug report**: You can review existing bug reports [here](https://github.com/inotia00/ReVanced_Extended/labels/Bug%20report).
        - **Check if this issue reproduces in unpatched apps as well**: Most bugs can also be reproduced in unpatched apps.
  - type: dropdown
    attributes:
      label: Type
      options:
        - Error while patching
        - Error at runtime
        - Cosmetic
        - Other
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Tools used
      options:
        - RVX Manager
        - rvx-builder
        - Revancify
        - CLI
    validations:
      required: true
  - type: textarea
    attributes:
      label: Application
      description: Write down the application and version where the issue occurs.
      placeholder: e.g. YouTube v18.45.43
    validations:
      required: true
  - type: textarea
    attributes:
      label: Bug description
      description: |
        - Describe your bug in detail
        - Add steps to reproduce the bug if possible (Step 1. ... Step 2. ...)
        - Add images and videos if possible
        - List used patches if applicable
    validations:
        required: true
  - type: textarea
    attributes:
      label: Error logs
      description: Exceptions can be captured by running `logcat | grep AndroidRuntime` in a shell.
      render: shell
  - type: textarea
    attributes:
      label: Solution
      description: If applicable, add a possible solution to the bug.
  - type: textarea
    attributes:
      label: Additional context
      description: Add additional context here.
  - type: textarea
    attributes:
      label: Device Environment
      description: Add your device environment.
      placeholder: Android 13, MIUI 14 ...
  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your bug report will be closed if you don't follow the checklist below.
      options:
        - label: This issue does not reproduce on unpatched YouTube or YT Music.
          required: true
        - label: This issue is not a duplicate of an existing bug report.
          required: true
        - label: I have chosen an appropriate title.
          required: true
        - label: All requested information has been provided properly.
          required: true
        - label: I have written the title and contents in English.
          required: true