name: ⭐ Feature request
description: Create a detailed request for a new feature.
title: 'feat: '
labels: ['Feature request']
body:
  - type: markdown
    attributes:
      value: |
        # ReVanced Extended feature request

        Before creating a new feature request, please keep the following in mind:

        - **Do not submit a duplicate feature request**: You can review existing feature requests [here](https://github.com/inotia00/ReVanced_Extended/labels/Feature%20request).
        - **Do not write feature requests targeting YouTube**: Due to too many feature requests targeting YouTube, DEV is no longer accepting them.
  - type: dropdown
    attributes:
      label: Application
      options:
        - YouTube Music
        - Reddit
    validations:
      required: true
  - type: textarea
    attributes:
      label: Feature description
      description: |
        - Describe your feature in detail
        - Add images, videos, links, examples, references, etc. if possible
        - Add the target application name in case you request a new patch
  - type: textarea
    attributes:
      label: Motivation
      description: | 
        A strong motivation is necessary for a feature request to be considered.
        
        - Why should this feature be implemented? 
        - What is the explicit use case?
        - What are the benefits?
        - What makes this feature important?
    validations:
      required: true
  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your issue will be closed if you haven't done these steps.
      options:
        - label: This is not a feature request for YouTube.
          required: true
        - label: This issue is not a duplicate of an existing feature request.
          required: true
        - label: I have chosen an appropriate title.
          required: true
        - label: All requested information has been provided properly.
          required: true
        - label: I have written the title and contents in English.
          required: true
