name: 📜 Suggestion
description: Leave any other suggestions about the patches or other things.
title: 'suggestion: '
labels: ['Suggestion']
body:
  - type: markdown
    attributes:
      value: |
        # ReVanced Extended suggestion

        Before creating a new suggestion, please keep the following in mind:

        - **Do not submit a duplicate suggestion**: You can review existing suggestions [here](https://github.com/inotia00/ReVanced_Extended/labels/Suggestion).
        - **Do not write feature requests**: This is a suggestion, not a feature request.
  - type: dropdown
    attributes:
      label: Application
      options:
        - YouTube
        - YouTube Music
        - Other
    validations:
      required: true
  - type: textarea
    attributes:
      label: Suggestion description
      description: |
        - Describe your suggestion in detail
        - Add images and videos if possible
  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your issue will be closed if you haven't done these steps.
      options:
        - label: This issue is not a duplicate of an existing suggestion.
          required: true
        - label: This is not a feature request.
          required: true
        - label: I have chosen an appropriate title.
          required: true
        - label: All requested information has been provided properly.
          required: true
        - label: I have written the title and contents in English.
          required: true
